<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit52107f6d0a74d8b0fbae617b152aa6e9
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Medoo\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Medoo\\' => 
        array (
            0 => __DIR__ . '/..' . '/catfan/medoo/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit52107f6d0a74d8b0fbae617b152aa6e9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit52107f6d0a74d8b0fbae617b152aa6e9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit52107f6d0a74d8b0fbae617b152aa6e9::$classMap;

        }, null, ClassLoader::class);
    }
}
